/* SLEEF library configuration for znver4 CPU */ 
#define SLEEF_ENABLED
#define SLEEF_DOUBLE_AVAILABLE
#define SLEEF_DOUBLE_VEC_AVAILABLE
#define SLEEF_VINT_IS_VLONG
#define SLEEF_VEC_512_AVAILABLE
#define HAVE_FMA32_512
#define HAVE_FMA64_512
#define SLEEF_VEC_256_AVAILABLE
#define HAVE_FMA32_256
#define HAVE_FMA64_256
#define SLEEF_VEC_128_AVAILABLE
#define HAVE_FMA32_128
#define HAVE_FMA64_128
